name: "Comprueba la existencia del contenedor de docker"
on:
  push:
    paths:
      - "proyectos/[34567].md"

jobs:
  docker_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Extrae usuario y nombre del repo
        uses: actions/github-script@v3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ There's no repo URL in this diff with required format")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Encontrado repo " + repo + " para usuario " + user )
                core.exportVariable('user',user)
                core.exportVariable('repo',repo)
            }
      - name: Descarga repo usuario y ejecuta contenedor
        uses: actions/checkout@v2
        with:
          repository: "${{env.user}}/${{env.repo}}"
      - name: Ejecuta contenedor
        run: |
          if test -f "DOCKER_USER"; then
            echo "Usuario de Docker alternativo"
            user=`cat DOCKER_USER`
          fi
          export CONTAINER=${user}/${repo}
          docker run -t -v `pwd`:/app/test ${CONTAINER,,}
