name: "Comprueba la existencia de historias de usuario"
on:
  push:
    paths:
      - "proyectos/[1234567].md"

jobs:
  user_story_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Busca historias de usuario
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ No hay ningún URL de un repositorio con el formato requerido en el diff")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Analizando repo " + repo + " del usuario 🔥" + user )
                const non_paginated_issues = await github.issues.listForRepo.endpoint.merge( { owner: user, repo: repo })
                const issues = await github.paginate( non_paginated_issues )
                const user_stories = issues.filter(
                    issue =>
                        issue.labels.filter( label => label.name === "user-stories" ).length > 0
                        && ( issue.title.includes('HU') || issue.title.includes('US') )
                        && issue.milestone
                )
                if ( user_stories.length > 0 ) {
                    console.log( " ✅ Hay al menos una historia de usuario " )
                } else {
                    core.setFailed( " ❌ No hay ninguna historia de usuario en el repo " )
                }
            }
